- name: install homebrew
  become: false
  shell: 'yes | /usr/bin/ruby -e "$(curl -fsSl https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  args:
    creates: /usr/local/bin/brew

- name: ensure homebrew is updated
  become: false
  homebrew:
    state: latest
    update_homebrew: yes

- name: tap homebrew caskroom/cask
  become: false
  homebrew_tap:
    tap: "caskroom/cask"

