set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set textwidth=800
colorscheme molokai
syntax enable
set backspace=2
set encoding=utf-8
set ignorecase
set number
set smartindent
set shiftround
set incsearch
set hlsearch
set noerrorbells
set nowrap
set smartcase
set showmatch
set cursorline
set laststatus=2
set mouse=a
set title
set background=dark
set nofoldenable
set autoread
set spell
:au FocusLost * silent! wa

