alias cic="set completion-ignore-case On"
alias flushDNS="dscacheutil -flushcache"
alias finderShowHidden='defaults write com.apple.finder ShowAllFiles TRUE'
alias finderHideHidden='defaults write com.apple.finder ShowAllFiles FALSE'
alias docs="cd ~/Documents"
alias temp="cd ~/Documents/temp"
alias projects="cd ~/Documents/Projects"
alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'
alias speedtest="speedtest-cli"
alias cleanTemp="rm -rf ~/Documents/temp/*"
alias rm="trash"
alias scanWifi="airport -s"
alias lock="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias dotFiles="cd ~/Documents/dotfiles"
alias yoda="ssh -i ~/.ssh/adair-tech.pem brad@52.15.95.69"
alias scripts="cd ~/Documents/scripts"
alias adair="cd ~/Documents/Personal/Projects/adair.tech"
alias screen="tmux"
