brew install ansible
brew install aws-shell
brew install awscli
brew install cask
brew install dockutil
brew install emacs
brew install gist
brew install highlight
brew install htop-osx
brew install hub
brew install jq
brew install maven
brew install mysql
brew install nmap
brew install node
brew install perl
brew install python
brew install python3
brew install ruby
brew install speedtest_cli
brew install thefuck
brew install vim
brew install watch
brew install wget
