brew cask install 1password
brew cask install angry-ip-scanner
brew cask install cheatsheet
brew cask install dash
brew cask install filezilla
brew cask install geekbench
brew cask install goofy
brew cask install knockknock
brew cask install postman
brew cask install qlcolorcode
brew cask install quicklook-json
brew cask install slack
brew cask install vagrant
brew cask install virtualbox
brew cask install java