brew install ansible
brew install archey
brew install autoconf
brew install automake
brew install awscli
brew install bash
brew install bash-completion
brew install boost
brew install cairo
brew install cask
brew install coreutils
brew install dark-mode
brew install dockutil
brew install doxygen
brew install emacs
brew install fontconfig
brew install freetype
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install gist
brew install git
brew install glib
brew install go
brew install gobject-introspection
brew install govendor
brew install graphite2
brew install harfbuzz
brew install highlight
brew install htop
brew install htop-osx
brew install hub
brew install icu4c
brew install imagemagick
brew install jenv
brew install jpeg
brew install jq
brew install libcroco
brew install libevent
brew install libffi
brew install libidn2
brew install libpng
brew install librsvg
brew install libtiff
brew install libtool
brew install libunistring
brew install libyaml
brew install lua
brew install mackup
brew install maven
brew install mtr
brew install mycli
brew install mysql
brew install nginx
brew install nmap
brew install node
brew install oniguruma
brew install openssl
brew install openssl@1.1
brew install packer
brew install pango
brew install pcre
brew install perl
brew install pixman
brew install pkg-config
brew install python
brew install python3
brew install readline
brew install ruby
brew install shared-mime-info
brew install solr@5.5
brew install speedtest-cli
brew install speedtest_cli
brew install sqlite
brew install ssh-copy-id
brew install terraform
brew install thefuck
brew install tmux
brew install trash
brew install tree
brew install utf8proc
brew install vim
brew install watch
brew install wget
brew install xz
brew install youtube-dl
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting
