brew cask install 1password
brew cask install amazon-workspaces
brew cask install angry-ip-scanner
brew cask install appcleaner
brew cask install atom
brew cask install basecamp
brew cask install coda
brew cask install dash
brew cask install docker
brew cask install firefox
brew cask install flux
brew cask install google-chrome
brew cask install hipchat
brew cask install ireadfast
brew cask install iterm2
brew cask install jump-desktop
brew cask install microsoft-office
brew cask install mongodb
brew cask install omnifocus
brew cask install scrivener
brew cask install sequel-pro
brew cask install slack
brew cask install sourcetree
brew cask install textexpander
brew cask install vagrant
brew cask install virtualbox
brew cask install virtualbox-extension-pack
brew cask install wireshark
brew cask install intellij-idea
