# Set true color
set -g default-terminal "screen-256color"
# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

#Split panes with | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

#Switch panes using Alt-arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse support
set -g mouse on

#Tokyo night theme config
set -g @theme_left_separator ''
set -g @theme_right_separator ''

set -g @plugin "janoamaral/tokyo-night-tmux"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'yardnsm/tmux-1password'
set -g @1password-account 'bradadair'
run '~/.tmux/plugins/tpm/tpm'
