---
general: 
  local_home: "{{ lookup('env','HOME') }}"

homebrew_packages:
  - ansible
  - archey
  - autoconf
  - automake
  - awscli
  - bash
  - bash-completion
  - bat
  - cask
  - coreutils
  - curl-openssl
  - diff-so-fancy
  - docker
  - dockutil
  - e2fsprogs
  - fzf
  - gist
  - git
  - git-extras
  - gnupg
  - gnutls
  - go
  - highlight
  - htop
  - httpd
  - httpie
  - hub
  - imagemagick
  - jenv
  - jq
  - mysql
  - mysql-client
  - ncdu
  - ncurses
  - nmap
  - node
  - packer
  - perl
  - php
  - prettyping
  - python
  - python3
  - speedtest-cli
  - ssh-copy-id
  - tcptraceroute
  - telnet
  - terraform
  - thefuck
  - tmux
  - trash
  - tree 
  - vim
  - watch
  - wget
  - youtube-dl
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting

cask_applications:
  - 1password
  - angry-ip-scanner
  - appcleaner
  - cheatsheet
  - dash
  - docker
  - firefox
  - flycut
  - font-fira-code
  - geekbench
  - goofy
  - google-chrome
  - harvest
  - iterm2
  - java
  - karabiner-elements
  - keepassxc
  - kitematic
  - postman
  - qlcolorcode
  - quicklook-json
  - rocket
  - sequel-pro
  - slack
  - sourcetree
  - sublime-text
  - vagrant
  - virtualbox
  - visual-studio-code
