#!/bin/bash
if hyprctl clients -j | grep -q '"class": "kitty-scratchpad"'; then
    hyprctl dispatch togglespecialworkspace term
else
    hyprctl dispatch exec "[workspace special:term silent] kitty --class kitty-scratchpad"
fi
