#!/bin/sh
# yazi-filepicker - Yazi wrapper for xdg-desktop-portal-termfilechooser
#
# Arguments from the portal:
#   $1 - "1" if multiple files can be chosen, "0" otherwise
#   $2 - "1" if a directory should be chosen, "0" otherwise
#   $3 - "0" if opening files, "1" if saving a file
#   $4 - If saving, the recommended save path (e.g. ~/Downloads/file.html)
#   $5 - Output path to write selected paths to (one per line)

multiple="$1"
directory="$2"
save="$3"
path="$4"
out="$5"

termcmd="${TERMCMD:-kitty}"

if [ "$save" = "1" ]; then
    # Save mode: navigate to target directory in yazi, then prompt for filename
    save_dir="$(dirname "$path")"
    save_name="$(basename "$path")"
    tmp_cwd=$(mktemp)

    "$termcmd" -- sh -c "
        yazi --cwd-file='$tmp_cwd' '$save_dir'
        chosen_dir=\$(cat '$tmp_cwd')
        rm -f '$tmp_cwd'
        if [ -n \"\$chosen_dir\" ]; then
            printf 'Save as [%s]: ' '$save_name'
            read -r filename
            filename=\"\${filename:-$save_name}\"
            if [ -n \"\$filename\" ]; then
                printf '%s/%s\n' \"\$chosen_dir\" \"\$filename\" > '$out'
            fi
        fi
    "
elif [ "$directory" = "1" ]; then
    # Directory mode: write cwd on quit, but also allow picking a file.
    # Some apps (e.g. Slack) incorrectly send directory=1 for file uploads.
    # If the user selects a file via --chooser-file, use that; otherwise fall
    # back to the cwd so legitimate directory pickers still work.
    tmp_cwd=$(mktemp)
    "$termcmd" -- sh -c "
        yazi --chooser-file='$out' --cwd-file='$tmp_cwd'
        if [ ! -s '$out' ]; then
            chosen_dir=\$(cat '$tmp_cwd')
            [ -n \"\$chosen_dir\" ] && printf '%s\n' \"\$chosen_dir\" > '$out'
        fi
        rm -f '$tmp_cwd'
    "
elif [ "$multiple" = "1" ]; then
    # Multi-select mode: space to mark, enter to confirm
    "$termcmd" -- sh -c "yazi --chooser-file='$out'"
else
    # Single file mode
    "$termcmd" -- sh -c "yazi --chooser-file='$out'"
fi
