##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

# Scratchpad terminal
windowrule = float on, match:class ^kitty-scratchpad$
windowrule = size 75% 40%, match:class ^kitty-scratchpad$

# File picker (yazi via xdg-desktop-portal-termfilechooser)
windowrule = float on, match:class ^filepicker$
windowrule = size 75% 75%, match:class ^filepicker$
windowrule = center on, match:class ^filepicker$

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false
